# Generated by Django 4.1.2 on 2022-10-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
